-- ----------------------------------------------------------------
-- Script name: 50_revoke_from_public.sql
-- Author: Sergio Artigas
-- Created on: Nov 19, 2024
-- Purpose: Create role to access schema objects.
-- Optional: Source schema can be locked down for security reasons.
-- ----------------------------------------------------------------
SET DEFINE ON
SET ECHO OFF
SET SQLBLANKLINES OFF
SET FEEDBACK OFF
SET HEADING OFF
SET VERIFY ON
SET WRAP OFF
SET TRIMSPOOL ON
SET TRIMOUT ON
SET PAGESIZE 0
SET LINESIZE 300

SPOOL script_006.sql APPEND

SELECT 'ALTER /* '||OBJECT_TYPE||' */ '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE = 'TYPE'
ORDER BY OBJECT_TYPE DESC
/

SELECT 'ALTER /* '||OBJECT_TYPE||' */ TYPE "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE BODY;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE = 'TYPE BODY'
ORDER BY OBJECT_TYPE DESC
/

SELECT 'ALTER /* '||OBJECT_TYPE||' */ '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE = 'SYNONYM'
ORDER BY OBJECT_TYPE DESC
/

SELECT 'ALTER /* '||OBJECT_TYPE||' */ '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE = 'VIEW'
ORDER BY OBJECT_TYPE DESC
/

SELECT 'ALTER /* '||OBJECT_TYPE||' */ '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE IN ('FUNCTION','PROCEDURE')
ORDER BY OBJECT_TYPE
/

SELECT 'ALTER /* '||OBJECT_TYPE||' */ '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE IN ('PACKAGE')
ORDER BY OBJECT_TYPE
/

SELECT 'ALTER /* '||OBJECT_TYPE||' */ '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE IN ('TRIGGER')
ORDER BY OBJECT_TYPE
/

SELECT 'ALTER /* '||OBJECT_TYPE||' */ PACKAGE "'||OWNER||'"."'||OBJECT_NAME||'" COMPILE BODY;'
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OBJECT_TYPE = 'PACKAGE BODY'
ORDER BY OBJECT_TYPE DESC
/

SPOOL OFF
